## EIA Brent-WTI Prices
#### Coverage: 2026 - 2017

In [1]:
from dotenv import load_dotenv
import requests
import pandas as pd
import os

load_dotenv()

True

In [2]:
EIA_API_KEY = os.getenv('EIA_API_KEY')
FRED_API_KEY = os.getenv('FRED_API_KEY')
START_DATE = os.getenv('START_DATE')

headers = {
    "X-Params": f"api_key={EIA_API_KEY}"
}

### Brent Crude Prices

In [3]:
series_id = 'RBRTE'
price_name = 'Brent_Price_USD'

In [4]:
series_id = 'RBRTE'
price_name = 'Brent_Price_USD'

# Build URL with api_key as a query parameter
url = (
    f"https://api.eia.gov/v2/petroleum/pri/spt/data/"
    f"?api_key={EIA_API_KEY}"
    f"&frequency=daily"
    f"&data[0]=value"
    f"&facets[series][]={series_id}"
    f"&start={START_DATE}"
    f"&sort[0][column]=period"
    f"&sort[0][direction]=desc"
    f"&length=5000"
)

In [5]:
series_id = 'RBRTE'
price_name = 'Brent_Price_USD'

# Build URL with api_key as a query parameter
url = (
    f"https://api.eia.gov/v2/petroleum/pri/spt/data/"
    f"?api_key={EIA_API_KEY}"
    f"&frequency=daily"
    f"&data[0]=value"
    f"&facets[series][]={series_id}"
    f"&start={START_DATE}"
    f"&sort[0][column]=period"
    f"&sort[0][direction]=desc"
    f"&length=5000"
)

In [6]:
response = requests.get(url)

if response.status_code == 200:
    data = response.json()['response']['data']
    df_brent = pd.DataFrame(data)
    
    # Process Date and value columns as per utils.py logic
    df_brent = df_brent[['period', 'value']]
    df_brent.rename(columns={'period': 'Date', 'value': price_name}, inplace=True)
    df_brent['Date'] = pd.to_datetime(df_brent['Date']).dt.tz_localize(None)
    
    print(f"Fetched {len(df_brent)} Brent records.")
    display(df_brent.head())
else:
    print(f"Failed Brent fetch: {response.status_code} - {response.text}")

Fetched 2363 Brent records.

        Date Brent_Price_USD
0 2026-04-27          113.89
1 2026-04-24          111.86
2 2026-04-23          113.25
3 2026-04-22          113.44
4 2026-04-21          106.14

In [7]:
# brent is a string
df_brent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2363 entries, 0 to 2362
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             2363 non-null   datetime64[ns]
 1   Brent_Price_USD  2363 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 37.1+ KB

In [8]:
# convert from str to num
df_brent["Date"] = pd.to_datetime(df_brent["Date"])
df_brent = df_brent.set_index("Date")
df_brent = df_brent.sort_index()
df_brent["Brent_Price_USD"] = pd.to_numeric(
    df_brent["Brent_Price_USD"],
    errors="coerce"
)

weekly_brent = df_brent.resample("W-TUE").agg(
    brent_close=("Brent_Price_USD", "last"),
    brent_mean=("Brent_Price_USD", "mean"),
)
# weekly_brent.index = weekly_brent.index + pd.Timedelta(days=3)
# weekly_brent.index.name = "week_monday"

In [9]:
weekly_brent

            brent_close  brent_mean
Date
2017-01-03        55.05      55.050
2017-01-10        53.20      54.610
2017-01-17        54.68      54.294
2017-01-24        54.70      54.298
2017-01-31        55.25      55.010
...                 ...         ...
2026-03-31       126.69     118.514
2026-04-07       138.21     128.460
2026-04-14       118.69     120.436
2026-04-21       106.14     107.946
2026-04-28       113.89     113.110

[487 rows x 2 columns]

In [10]:
weekly_brent.to_parquet("../data/semi-cleaned/brent_weekly.parquet")
weekly_brent.tail()

            brent_close  brent_mean
Date
2026-03-31       126.69     118.514
2026-04-07       138.21     128.460
2026-04-14       118.69     120.436
2026-04-21       106.14     107.946
2026-04-28       113.89     113.110

### WTI Crude Prices

In [11]:
series_id = 'RWTC'
price_name = 'WTI_Price_USD'

In [12]:
url = (
    f"https://api.eia.gov/v2/petroleum/pri/spt/data/"
    f"?api_key={EIA_API_KEY}"
    f"&frequency=daily"
    f"&data[0]=value"
    f"&facets[series][]={series_id}"
    f"&start={START_DATE}"
    f"&sort[0][column]=period"
    f"&sort[0][direction]=desc"
    f"&length=5000"
)

In [13]:
response = requests.get(url)

if response.status_code == 200:
    data = response.json()['response']['data']
    df_wti = pd.DataFrame(data)
    
    df_wti = df_wti[['period', 'value']]
    df_wti.rename(columns={'period': 'Date', 'value': price_name}, inplace=True)
    df_wti['Date'] = pd.to_datetime(df_wti['Date']).dt.tz_localize(None)
    
    print(f"Fetched {len(df_wti)} WTI records.")
    display(df_wti.head())

Fetched 2331 WTI records.

        Date WTI_Price_USD
0 2026-04-27         99.89
1 2026-04-24         98.42
2 2026-04-23         99.27
3 2026-04-22         94.76
4 2026-04-21         93.64

In [14]:
df_wti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2331 entries, 0 to 2330
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           2331 non-null   datetime64[ns]
 1   WTI_Price_USD  2331 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 36.6+ KB

In [15]:
df_wti = df_wti.set_index("Date").sort_index()
df_wti["WTI_Price_USD"] = pd.to_numeric(df_wti["WTI_Price_USD"], errors="coerce")

weekly_wti = df_wti.resample("W-TUE").agg(
    wti_close=("WTI_Price_USD", "last"),
    wti_mean=("WTI_Price_USD", "mean"),
)
# weekly_wti.index = weekly_wti.index + pd.Timedelta(days=3)
# weekly_wti.index.name = "week_monday"

In [16]:
weekly_wti.to_parquet("../data/semi-cleaned/wti_weekly.parquet")
weekly_wti.tail()

            wti_close  wti_mean
Date
2026-03-31     102.86    99.300
2026-04-07     114.58   110.930
2026-04-14      93.07    97.584
2026-04-21      93.64    92.022
2026-04-28      99.89    98.085

# FRED Observations Endpoint

In [17]:
url = "https://api.stlouisfed.org/fred/series/observations"

In [18]:
series_id = 'POILDUBUSDM'  # Dubai Crude Global Price
price_name = 'Dubai_Crude_USD'

In [19]:
params = {
    'series_id': series_id,
    'api_key': FRED_API_KEY,
    'file_type': 'json',
    'observation_start': START_DATE,
    'sort_order': 'desc'
}

In [20]:
response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()
    observations = data.get('observations', [])
    
    df_dubai = pd.DataFrame(observations)
    
    # Keep only the date and value columns
    df_dubai = df_dubai[['date', 'value']]
    df_dubai.rename(columns={'date': 'Date', 'value': price_name}, inplace=True)
    
    # 1. Convert Date to Datetime
    df_dubai['Date'] = pd.to_datetime(df_dubai['Date'])
    
    # 2. Convert Value to Numeric. 
    # FRED uses '.' for missing values; 'coerce' turns them into actual NaNs
    df_dubai[price_name] = pd.to_numeric(df_dubai[price_name], errors='coerce')
    
    # 3. Drop rows with NaN (missing prices)
    df_dubai.dropna(subset=[price_name], inplace=True)
    
    # Reset index after dropping rows
    df_dubai.reset_index(drop=True, inplace=True)
    
    print(f"Fetched and cleaned {len(df_dubai)} records for Dubai Crude.")
    display(df_dubai.head())
else:
    print(f"Failed fetch: {response.status_code} - {response.text}")

Fetched and cleaned 111 records for Dubai Crude.

        Date  Dubai_Crude_USD
0 2026-03-01       126.706364
1 2026-02-01        68.508500
2 2026-01-01        62.728182
3 2025-12-01        61.830000
4 2025-11-01        64.355500

In [21]:
df_dubai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             111 non-null    datetime64[ns]
 1   Dubai_Crude_USD  111 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.9 KB

In [22]:
# if Date is still a column
df_dubai = df_dubai.set_index("Date").sort_index()
# if Date is already the index, just do:
# df_dubai = df_dubai.sort_index()

df_dubai["Dubai_Crude_USD"] = pd.to_numeric(df_dubai["Dubai_Crude_USD"], errors="coerce")

# monthly -> ffill to daily -> weekly
daily_idx = pd.date_range(df_dubai.index.min(), "2026-05-04", freq="D")
dubai_daily = df_dubai.reindex(daily_idx).ffill()
dubai_daily.index.name = "date"

weekly_dubai = dubai_daily.resample("W-TUE").agg(
    dubai_close=("Dubai_Crude_USD", "last"),
)
# weekly_dubai.index = weekly_dubai.index + pd.Timedelta(days=3)
# weekly_dubai.index.name = "week_monday"

weekly_dubai.to_parquet("../data/semi-cleaned/dubai_crude_weekly.parquet")
weekly_dubai.tail()

            dubai_close
date
2026-04-07   126.706364
2026-04-14   126.706364
2026-04-21   126.706364
2026-04-28   126.706364
2026-05-05   126.706364

In [23]:
pd.read_parquet("../data/semi-cleaned/dubai_crude_weekly.parquet")

            dubai_close
date
2017-01-03    53.569091
2017-01-10    53.569091
2017-01-17    53.569091
2017-01-24    53.569091
2017-01-31    53.569091
...                 ...
2026-04-07   126.706364
2026-04-14   126.706364
2026-04-21   126.706364
2026-04-28   126.706364
2026-05-05   126.706364

[488 rows x 1 columns]

In [24]:
pd.read_parquet("../data/semi-cleaned/wti_weekly.parquet")

            wti_close  wti_mean
Date
2017-01-03      52.36   52.3600
2017-01-10      50.82   52.7560
2017-01-17      52.45   52.5025
2017-01-24      52.38   51.9980
2017-01-31      52.75   52.7880
...               ...       ...
2026-03-31     102.86   99.3000
2026-04-07     114.58  110.9300
2026-04-14      93.07   97.5840
2026-04-21      93.64   92.0220
2026-04-28      99.89   98.0850

[487 rows x 2 columns]

In [25]:
pd.read_parquet("../data/semi-cleaned/brent_weekly.parquet")

            brent_close  brent_mean
Date
2017-01-03        55.05      55.050
2017-01-10        53.20      54.610
2017-01-17        54.68      54.294
2017-01-24        54.70      54.298
2017-01-31        55.25      55.010
...                 ...         ...
2026-03-31       126.69     118.514
2026-04-07       138.21     128.460
2026-04-14       118.69     120.436
2026-04-21       106.14     107.946
2026-04-28       113.89     113.110

[487 rows x 2 columns]