In [22]:
import yfinance as yf
import pandas as pd

In [23]:
rb = yf.download("RB=F", start="2015-01-01",
                  auto_adjust=False, multi_level_index=False)

[*********************100%***********************]  1 of 1 completed

In [24]:
rb

            Adj Close   Close    High     Low    Open  Volume
Date
2015-01-02     1.4334  1.4334  1.5072  1.4287  1.4806   42774
2015-01-05     1.3814  1.3814  1.4404  1.3615  1.4403   46187
2015-01-06     1.3543  1.3543  1.3989  1.3437  1.3750   61161
2015-01-07     1.3376  1.3376  1.3675  1.3110  1.3451   56396
2015-01-08     1.3409  1.3409  1.3529  1.3127  1.3346   62629
...               ...     ...     ...     ...     ...     ...
2026-04-28     3.5604  3.5604  3.5790  3.4586  3.4913   26257
2026-04-29     3.7411  3.7411  3.7684  3.5525  3.5747   23035
2026-04-30     3.7715  3.7715  3.8232  3.6846  3.7535   71871
2026-05-01     3.5952  3.5952  3.6768  3.5355  3.6311   71871
2026-05-04     3.6399  3.6399  3.6993  3.5400  3.5690    6902

[2851 rows x 6 columns]

In [25]:
rb.isnull().sum()

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [26]:
rb = rb[["Close"]].copy()
rb.columns = ["mops_rbob"]
rb = rb.reset_index()
rb.columns = ["date", "mops_rbob"]
rb = rb.set_index("date").sort_index()

In [46]:
# weekly aggregation (just close + mean since high/low/close are basically same)
weekly_rb = rb.resample("W-FRI").last()
weekly_rb.columns = ["mops_rbob"]
weekly_rb["mops_rbob_mean"] = rb.resample("W-FRI").mean()

# Anchor to Monday
weekly_rb.index = weekly_rb.index - pd.Timedelta(days=4)
weekly_rb.index.name = "week_start"

In [47]:
# convert from gallon to barrel
weekly_rb['mops_rbob'], weekly_rb['mops_rbob_mean'] = weekly_rb['mops_rbob'] * 42, weekly_rb['mops_rbob_mean'] * 42
weekly_rb

             mops_rbob  mops_rbob_mean
week_start
2014-12-29   60.202801       60.202801
2015-01-05   55.574399       56.594159
2015-01-12   57.069602       55.035960
2015-01-19   56.611801       55.828502
2015-01-26   59.438400       56.957881
...                ...             ...
2026-04-06  127.566605      131.521320
2026-04-13  126.201603      129.302881
2026-04-20  145.429200      139.517280
2026-04-27  150.998403      152.537282
2026-05-04  152.875799      152.875799

[593 rows x 2 columns]

In [48]:
weekly_rb.to_parquet("data/semi-cleaned/mops_rbob_weekly.parquet")

In [49]:
weekly_rb

             mops_rbob  mops_rbob_mean
week_start
2014-12-29   60.202801       60.202801
2015-01-05   55.574399       56.594159
2015-01-12   57.069602       55.035960
2015-01-19   56.611801       55.828502
2015-01-26   59.438400       56.957881
...                ...             ...
2026-04-06  127.566605      131.521320
2026-04-13  126.201603      129.302881
2026-04-20  145.429200      139.517280
2026-04-27  150.998403      152.537282
2026-05-04  152.875799      152.875799

[593 rows x 2 columns]

In [45]:
trymoto = pd.read_parquet('data/semi-cleaned/mops_rbob_weekly.parquet')
trymoto

             mops_rbob  mops_rbob_mean
week_start
2014-12-29   60.202801       60.202801
2015-01-05   55.574399       56.594159
2015-01-12   57.069602       55.035960
2015-01-19   56.611801       55.828502
2015-01-26   59.438400       56.957881
...                ...             ...
2026-04-06  127.566605      131.521320
2026-04-13  126.201603      129.302881
2026-04-20  145.429200      139.517280
2026-04-27  150.998403      152.537282
2026-05-04  152.875799      152.875799

[593 rows x 2 columns]